
    create table tb_ordem_de_servico (
       id int8 generated by default as identity,
        data_cadastro TIMESTAMP WITHOUT TIME ZONE,
        descricao_problema TEXT,
        descricao_solucao TEXT,
        equipamento varchar(255),
        patrimonio varchar(255),
        prioridade varchar(255),
        setor varchar(255),
        status varchar(255),
        servidor_id int8,
        primary key (id)
    );

    create table tb_servidor (
       id int8 generated by default as identity,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    alter table if exists tb_ordem_de_servico 
       add constraint FKi5goq43eellsuu7q0l4dhjtg9 
       foreign key (servidor_id) 
       references tb_servidor;
